### ISSUE TITLE
Forge's recent versions causes the plugin to not load correctly

### ISSUE THREAD

**Issue by yaroslav4167** [Yeregorix/AntiXray#3]
I'm upgrade to new spongeForge version and there was this error ='/
Console spam:
```
[00:58:01] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Modify$Impl to Plugin{id=antixray, name=AntiXray, version=1.2.7, description=A powerful solution against xray users, authors=[Yeregorix], source=/home/Public/1TB-SG/BioTech/./plugins/(P)AntiXray-1.2.7.jar}
java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to net.smoofyuniverse.antixray.impl.internal.InternalWorld
        at net.smoofyuniverse.antixray.event.WorldEventListener.deobfuscateSurrounding(WorldEventListener.java:111) ~[WorldEventListener.class:?]
        at net.smoofyuniverse.antixray.event.WorldEventListener.lambda$onBlockChange$1(WorldEventListener.java:79) ~[WorldEventListener.class:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_151]
        at net.smoofyuniverse.antixray.event.WorldEventListener.onBlockChange(WorldEventListener.java:79) ~[WorldEventListener.class:?]
        at org.spongepowered.common.event.listener.ChangeBlockEventListener_WorldEventListener_onBlockChange66.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) ~[SpongeModEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:408) ~[SpongeModEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:392) ~[SpongeModEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) ~[SpongeEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) ~[SpongeImpl.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:605) ~[TrackingUtil.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:524) ~[TrackingUtil.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$unwind$0(BlockTickPhaseState.java:84) ~[BlockTickPhaseState.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.context.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:69) [CapturedSupplier.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.unwind(BlockTickPhaseState.java:84) [BlockTickPhaseState.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.unwind(BlockTickPhaseState.java:51) [BlockTickPhaseState.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:213) [PhaseTracker.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439) [PhaseContext.class:1.12.2-2690-7.1.0-BETA-3112]
        at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:326) [TrackingUtil.class:1.12.2-2690-7.1.0-BETA-3112]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2167) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Yeregorix** [comment]
What is your SpongeForge version and what was the previous ? 
Can you paste me a copy of your full log (logs/fml-server-latest.log) using a service such as pastebin.com ?

**Comment by yaroslav4167** [comment]
Previous sponge version: 1.12.2-2655-7.1.0-BETA-3105
Today i'm upgraded to 1.12.2-2703-7.1.0-BETA-3116 version. The error has remained.
[fml-server-latest.log](https://pastebin.com/wdCm4dDe) [latest.log](https://pastebin.com/4iFpc4pW)

**Comment by Yeregorix** [comment]
`[21:21:09] [Server thread/ERROR] [AntiXray]: !!WARNING!! AntiXray was not loaded correctly. Be sure that the jar file is at the root of your mods folder!` line 1751 in latest.log

Are you sure that the jar file is at the root of your mods folder ^^ ?

**Comment by yaroslav4167** [comment]
I configured sponge so that the plugins are in the "Plugins" folder.
I tried to move the plugin to the mods directory, but the server gave an [error](http://bit.ly/2shkFE1).

**Comment by Yeregorix** [comment]
I've found what was causing your issue (DuplicateModsFoundException), it will be fixed in the next release.

**Comment by yaroslav4167** [comment]
Thank you =D

**Comment by yaroslav4167** [comment]
I installed version from git and get [crash](http://bit.ly/2GS2n1o)
Is this the problem of AntiXray or Sonar (ParticalLogistics)?

**Comment by Yeregorix** [comment]
The version from git is still in development, it's normal to have issues with until 1.3.0 is fully tested, fixed and released.
Thanks anyway for reporting theses issues.

**Comment by Yeregorix** [comment]
The incompatibility with ParticalLogistics should be fixed in the latest commit.
For your second issue I will need more time.

**Comment by Yeregorix** [comment]
The second issue is now fixed.
If you have others issues, feel free to report them in separate pages.
